### PR TITLE
Improve code review guide line

### PR DESCRIPTION
**Pull request by colmarius**
Code review meeting notes after reviewing current workflow.

### CODE REVIEW

**Comment by colmarius** [comment]
@BuddyBroker/developers Hi team, please give your feedback on code review improvements.

**Comment by andrzejtrzaska** [comment]
:+1:

**Comment by MagdaMalinowska** [comment]
:+1:

**Comment by AniaCodequest** [comment]
[?]

2015-06-24 13:26 GMT+02:00 Magdalena Malinowska <notifications@github.com>:

**Comment by colmarius** [comment]
Thank you guys! :rainbow: for @AniaCodequest

**Comment by AniaCodequest** [comment]
@colmarius you are awesome! Thank you!!!

**Pull request merged**
