### PR TITLE
Ruby style ignore expect block count

### PR DESCRIPTION
**Pull request by colmarius**
Block delimiter enforced from line_count_based to semantic check. Ignore "expect" method from check.

Support both styles.

already valid:

 ```ruby
expect { something_bad }.to raise_error(SomeError)
```

currently as offence, accepted after this change:

 ```ruby
expect {
  something_really_bad.call(
    to_happen,
    blabla
  )
}.to raise_error(SomeError)
```

### CODE REVIEW

**Comment by colmarius** [comment]
@MagdaMalinowska @andrzejtrzaska what do you think?

**Comment by andrzejtrzaska** [comment]
@colmarius this makes sense to me, approved

**Comment by colmarius** [comment]
Thanks @andrzejtrzaska, will update projects based on this change.

@MagdaMalinowska let me know your feedback too :-). Merging in.

**Comment by colmarius** [comment]
@MagdaMalinowska @andrzejtrzaska update on what changes with blocks from checking line count to checking semantic (procedural or functional usage)  `{ .. }` vs `do .. end` 

See this article from avdi grimm on [The Procedure/Function Block Convention in Ruby]

[The Procedure/Function Block Convention in Ruby]: http://devblog.avdi.org/2011/07/26/the-procedurefunction-block-convention-in-ruby/

**Pull request merged**
